/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 gallery.glb
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF(
    "/gallery.glb"
  );
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.stucco_4.geometry}
        material={nodes.stucco_4.material}
        position={[0.947, 2.016, 0.002]}
      />
      <mesh
        geometry={nodes.stucco_1.geometry}
        material={nodes.stucco_1.material}
        position={[-0.057, 2.027, -3.5]}
      />
      <mesh
        geometry={nodes.stucco_3.geometry}
        material={nodes.stucco_3.material}
        position={[5.047, 1.857, 0.002]}
      />
      <mesh
        geometry={nodes.stucco_2.geometry}
        material={nodes.stucco_2.material}
        position={[-0.056, 1.995, 3.445]}
      />
      <mesh
        geometry={nodes.rzezba.geometry}
        material={nodes.rzezba.material}
        position={[-6.265, 0.915, 11.301]}
        rotation={[
          -Math.PI,
          Math.PI / 6,
          -Math.PI,
        ]}
        scale={0.001}
      />
      <mesh
        geometry={nodes.obraz26.geometry}
        material={nodes.obraz26.material}
        position={[-0.118, 1.42, -10.21]}
      />
      <mesh
        geometry={nodes.obraz23.geometry}
        material={nodes.obraz23.material}
        position={[-0.118, 1.42, -3.981]}
      />
      <mesh
        geometry={nodes.obraz22.geometry}
        material={nodes.obraz22.material}
        position={[-0.118, 1.42, 4.027]}
      />
      <mesh
        geometry={nodes.obraz19.geometry}
        material={nodes.obraz19.material}
        position={[-0.118, 1.42, 10.438]}
      />
      <mesh
        geometry={nodes.obraz1.geometry}
        material={nodes.obraz1.material}
        position={[5.121, 1.42, 5.499]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.obraz16.geometry}
        material={nodes.obraz16.material}
        position={[0.003, 1.42, 4.338]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.obraz13.geometry}
        material={nodes.obraz13.material}
        position={[0.003, 1.42, -7.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.obraz8.geometry}
        material={nodes.obraz8.material}
        position={[4.996, 1.42, -4.867]}
      />
      <mesh
        geometry={nodes.obraz11.geometry}
        material={nodes.obraz11.material}
        position={[4.996, 1.42, 2.759]}
      />
      <mesh
        geometry={nodes.obraz4.geometry}
        material={nodes.obraz4.material}
        position={[5.119, 1.42, -0.427]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.obraz7.geometry}
        material={nodes.obraz7.material}
        position={[5.119, 1.42, -5.863]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.ramka26.geometry}
        material={nodes.ramka26.material}
        position={[-0.125, 1.42, -10.21]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka23.geometry}
        material={nodes.ramka23.material}
        position={[-0.125, 1.42, -3.98]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka22.geometry}
        material={nodes.ramka22.material}
        position={[-0.125, 1.42, 4.027]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka19.geometry}
        material={nodes.ramka19.material}
        position={[-0.125, 1.42, 10.438]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka1.geometry}
        material={nodes.ramka1.material}
        position={[5.128, 1.42, 5.499]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka16.geometry}
        material={nodes.ramka16.material}
        position={[0.01, 1.42, 4.338]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka13.geometry}
        material={nodes.ramka13.material}
        position={[0.01, 1.42, -7.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka8.geometry}
        material={nodes.ramka8.material}
        position={[4.989, 1.42, -4.867]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka11.geometry}
        material={nodes.ramka11.material}
        position={[4.989, 1.42, 2.759]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka4.geometry}
        material={nodes.ramka4.material}
        position={[5.126, 1.42, -0.428]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka7.geometry}
        material={nodes.ramka7.material}
        position={[5.126, 1.42, -5.863]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka24.geometry}
        material={nodes.ramka24.material}
        position={[-0.123, 1.42, -5.717]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka10.geometry}
        material={nodes.ramka10.material}
        position={[4.991, 1.42, -1.663]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka20.geometry}
        material={nodes.ramka20.material}
        position={[-0.123, 1.42, 7.955]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka14.geometry}
        material={nodes.ramka14.material}
        position={[0.008, 1.42, -5.93]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka17.geometry}
        material={nodes.ramka17.material}
        position={[0.008, 1.42, 6.704]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka3.geometry}
        material={nodes.ramka3.material}
        position={[5.124, 1.42, 1.416]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka6.geometry}
        material={nodes.ramka6.material}
        position={[5.124, 1.42, -4.03]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.obraz25.geometry}
        material={nodes.obraz25.material}
        position={[-0.116, 1.444, -8.374]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz21.geometry}
        material={nodes.obraz21.material}
        position={[-0.116, 1.444, 5.888]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz18.geometry}
        material={nodes.obraz18.material}
        position={[0.002, 1.444, 9.742]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz15.geometry}
        material={nodes.obraz15.material}
        position={[0.002, 1.444, -4.049]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz9.geometry}
        material={nodes.obraz9.material}
        position={[4.998, 1.444, -3.368]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz5.geometry}
        material={nodes.obraz5.material}
        position={[5.118, 1.444, -1.967]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz2.geometry}
        material={nodes.obraz2.material}
        position={[5.118, 1.444, 3.955]}
        rotation={[Math.PI, 0, -Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.obraz24.geometry}
        material={nodes.obraz24.material}
        position={[-0.123, 1.42, -5.717]}
      />
      <mesh
        geometry={nodes.obraz20.geometry}
        material={nodes.obraz20.material}
        position={[-0.123, 1.42, 7.955]}
      />
      <mesh
        geometry={nodes.obraz17.geometry}
        material={nodes.obraz17.material}
        position={[0.008, 1.42, 6.704]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        geometry={nodes.obraz14.geometry}
        material={nodes.obraz14.material}
        position={[0.008, 1.42, -5.93]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.obraz10.geometry}
        material={nodes.obraz10.material}
        position={[4.991, 1.42, -1.663]}
      />
      <mesh
        geometry={nodes.obraz6.geometry}
        material={nodes.obraz6.material}
        position={[5.124, 1.42, -4.03]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.obraz3.geometry}
        material={nodes.obraz3.material}
        position={[5.124, 1.42, 1.416]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.obraz12.geometry}
        material={nodes.obraz12.material}
        position={[4.998, 1.444, 5.489]}
        rotation={[0, 0, Math.PI / 2]}
        scale={[0.009, 0.01, 0.008]}
      />
      <mesh
        geometry={nodes.background.geometry}
        material={nodes.background.material}
        position={[0.048, 2.97, -0.539]}
        scale={39.411}
      />
      <mesh
        geometry={nodes.ramka25.geometry}
        material={nodes.ramka25.material}
        position={[-0.108, 1.42, -8.37]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka9.geometry}
        material={nodes.ramka9.material}
        position={[4.998, 1.444, -3.368]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka12.geometry}
        material={nodes.ramka12.material}
        position={[4.998, 1.444, 5.489]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka21.geometry}
        material={nodes.ramka21.material}
        position={[-0.116, 1.444, 5.888]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka15.geometry}
        material={nodes.ramka15.material}
        position={[0.002, 1.444, -4.049]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka18.geometry}
        material={nodes.ramka18.material}
        position={[0.002, 1.444, 9.742]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka2.geometry}
        material={nodes.ramka2.material}
        position={[5.118, 1.444, 3.955]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.ramka5.geometry}
        material={nodes.ramka5.material}
        position={[5.118, 1.444, -1.967]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.2, 0.45, 0.321]}
      />
      <mesh
        geometry={nodes.azur.geometry}
        material={nodes.azur.material}
        position={[9.776, 6, -6.079]}
      />
      <mesh
        geometry={nodes["szyba-okno"].geometry}
        material={nodes["szyba-okno"].material}
        position={[9.627, 6, -6.106]}
      />
      <mesh
        geometry={
          nodes["metalowe-listwy"].geometry
        }
        material={
          nodes["metalowe-listwy"].material
        }
        position={[0, 0, 3.98]}
        scale={0.01}
      />
      <mesh
        geometry={nodes["lampy-stojace"].geometry}
        material={nodes["lampy-stojace"].material}
        position={[-6.172, 2.017, 11.166]}
      />
      <mesh
        geometry={nodes.Lampa.geometry}
        material={nodes.Lampa.material}
        position={[5.606, 2.886, 5.5]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa002.geometry}
        material={nodes.Lampa002.material}
        position={[5.606, 2.886, 1.431]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa004.geometry}
        material={nodes.Lampa004.material}
        position={[5.606, 2.886, -0.421]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa006.geometry}
        material={nodes.Lampa006.material}
        position={[5.606, 2.886, -4.027]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa008.geometry}
        material={nodes.Lampa008.material}
        position={[0.493, 2.886, -7.996]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa010.geometry}
        material={nodes.Lampa010.material}
        position={[-0.616, 2.886, 7.953]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa012.geometry}
        material={nodes.Lampa012.material}
        position={[-0.616, 2.886, 10.433]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa014.geometry}
        material={nodes.Lampa014.material}
        position={[0.496, 2.886, 4.338]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa024.geometry}
        material={nodes.Lampa024.material}
        position={[-0.618, 2.886, 7.952]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa030.geometry}
        material={nodes.Lampa030.material}
        position={[-0.616, 2.886, 7.951]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa036.geometry}
        material={nodes.Lampa036.material}
        position={[-0.618, 2.886, -10.162]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa052.geometry}
        material={nodes.Lampa052.material}
        position={[-0.618, 2.886, -4.13]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa054.geometry}
        material={nodes.Lampa054.material}
        position={[-0.618, 2.886, 4.029]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa016.geometry}
        material={nodes.Lampa016.material}
        position={[5.606, 2.886, 3.96]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa018.geometry}
        material={nodes.Lampa018.material}
        position={[0.496, 2.886, -4.05]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa020.geometry}
        material={nodes.Lampa020.material}
        position={[0.496, 2.886, 9.739]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      >
        <mesh
          geometry={nodes.emisyjny002.geometry}
          material={nodes.emisyjny002.material}
          scale={100}
        />
      </mesh>
      <mesh
        geometry={nodes.Lampa038.geometry}
        material={nodes.Lampa038.material}
        position={[-0.616, 2.886, -8.25]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa040.geometry}
        material={nodes.Lampa040.material}
        position={[-0.616, 2.886, 5.889]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa042.geometry}
        material={nodes.Lampa042.material}
        position={[0.495, 2.886, 6.709]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa022.geometry}
        material={nodes.Lampa022.material}
        position={[5.606, 2.886, -1.96]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa026.geometry}
        material={nodes.Lampa026.material}
        position={[5.606, 2.886, -5.87]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa028.geometry}
        material={nodes.Lampa028.material}
        position={[4.524, 2.886, 5.489]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa032.geometry}
        material={nodes.Lampa032.material}
        position={[4.524, 2.886, -1.67]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa034.geometry}
        material={nodes.Lampa034.material}
        position={[4.524, 2.886, 2.77]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa044.geometry}
        material={nodes.Lampa044.material}
        position={[0.496, 2.886, -5.931]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa046.geometry}
        material={nodes.Lampa046.material}
        position={[-0.616, 2.886, -5.81]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa048.geometry}
        material={nodes.Lampa048.material}
        position={[4.524, 2.886, -3.367]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.Lampa050.geometry}
        material={nodes.Lampa050.material}
        position={[4.524, 2.886, -4.876]}
        scale={0.01}
      />
      <mesh
        geometry={nodes["rama-okienna"].geometry}
        material={nodes["rama-okienna"].material}
        position={[0.01, 0, 0]}
        scale={0.01}
      />
      <mesh
        geometry={
          nodes["listwy-przypodlogowe"].geometry
        }
        material={
          nodes["listwy-przypodlogowe"].material
        }
        position={[-0.106, 0.03, 12]}
        rotation={[-Math.PI, 0, 0]}
        scale={-0.01}
      />
      <mesh
        geometry={nodes.emisyjny003.geometry}
        material={nodes.emisyjny003.material}
        position={[0.53, 15.72, 1.22]}
        rotation={[0, 0, Math.PI]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.emisyjny.geometry}
        material={nodes.emisyjny.material}
        position={[-7.75, 6.54, -8.82]}
        rotation={[0, -0.157, 0]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.emisyjny001.geometry}
        material={nodes.emisyjny001.material}
        position={[-6.172, 2.017, 11.166]}
      />
      <mesh
        geometry={
          nodes["podloga-jodelka"].geometry
        }
        material={
          nodes["podloga-jodelka"].material
        }
      />
      <mesh
        geometry={
          nodes["podloga-jodelka002"].geometry
        }
        material={
          nodes["podloga-jodelka002"].material
        }
        position={[6.287, 0, -4.007]}
      />
      <mesh
        geometry={nodes.grubosc002.geometry}
        material={nodes.grubosc002.material}
        position={[6.466, 0, -4.482]}
      />
      <mesh
        geometry={nodes.grubosc001.geometry}
        material={nodes.grubosc001.material}
        position={[6.466, -0.337, -4.482]}
      />
      <mesh
        geometry={nodes["podloga-metal"].geometry}
        material={nodes["podloga-metal"].material}
        scale={0.01}
      />
      <mesh
        geometry={nodes.sciezka.geometry}
        material={nodes.sciezka.material}
        scale={0.01}
      />
      <mesh
        geometry={nodes.sufit.geometry}
        material={nodes.sufit.material}
        position={[1.037, 12, -0.41]}
        scale={0.01}
      />
      <mesh
        geometry={nodes.zewn_22.geometry}
        material={nodes.zewn_22.material}
        position={[3.48, 10, -8.699]}
      />
      <mesh
        geometry={nodes.zewn_13.geometry}
        material={nodes.zewn_13.material}
        position={[0.885, 10.666, -12.69]}
      />
      <mesh
        geometry={nodes.zewn_24.geometry}
        material={nodes.zewn_24.material}
        position={[4.052, 6.002, -12.047]}
      />
      <mesh
        geometry={nodes.zewn_26.geometry}
        material={nodes.zewn_26.material}
        position={[-10.59, 1.86, -13.96]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[0.072, 0.04, 0.002]}
      />
      <mesh
        geometry={nodes.zewn_2.geometry}
        material={nodes.zewn_2.material}
        position={[-5.493, 2, -3.943]}
      />
      <mesh
        geometry={nodes.zewn_11.geometry}
        material={nodes.zewn_11.material}
        position={[0.917, 1.333, -13.923]}
      />
      <mesh
        geometry={nodes.zewn_1.geometry}
        material={nodes.zewn_1.material}
        position={[-9.256, 2, 6.471]}
      />
      <mesh
        geometry={nodes.zewn_5.geometry}
        material={nodes.zewn_5.material}
        position={[-8.544, 10.667, -3.824]}
      />
      <mesh
        geometry={nodes.zewn_19.geometry}
        material={nodes.zewn_19.material}
        position={[2.156, 9.987, 8.882]}
      />
      <mesh
        geometry={nodes.zewn_10.geometry}
        material={nodes.zewn_10.material}
        position={[8.193, 10.667, 0.501]}
      />
      <mesh
        geometry={nodes.zewn_7.geometry}
        material={nodes.zewn_7.material}
        position={[-1.086, 10.667, 13.956]}
      />
      <mesh
        geometry={nodes.zewn_6.geometry}
        material={nodes.zewn_6.material}
        position={[-1.086, 4, 13.998]}
      />
      <mesh
        geometry={nodes.zewn_20.geometry}
        material={nodes.zewn_20.material}
        position={[2.142, 6, 8.857]}
      />
      <mesh
        geometry={nodes.zewn_21.geometry}
        material={nodes.zewn_21.material}
        position={[2.156, 2.013, 8.882]}
      />
      <mesh
        geometry={nodes.zewn_18.geometry}
        material={nodes.zewn_18.material}
        position={[-1.925, 5.966, 5.98]}
      />
      <mesh
        geometry={nodes.zewn_17.geometry}
        material={nodes.zewn_17.material}
        position={[-8.278, 10.034, -9.649]}
      />
      <mesh
        geometry={nodes.zewn_16.geometry}
        material={nodes.zewn_16.material}
        position={[-8.939, 6.009, 3.232]}
      />
      <mesh
        geometry={nodes.zewn_3.geometry}
        material={nodes.zewn_3.material}
        position={[-9.752, 6.001, 8.983]}
      />
      <mesh
        geometry={nodes.zewn_15.geometry}
        material={nodes.zewn_15.material}
        position={[-9.323, 2.441, 7.896]}
      />
      <mesh
        geometry={nodes.zewn_4.geometry}
        material={nodes.zewn_4.material}
        position={[-8.168, 5.715, -8.441]}
      />
      <mesh
        geometry={nodes.zewn_25.geometry}
        material={nodes.zewn_25.material}
        position={[2.482, 2.373, -13.287]}
      />
      <mesh
        geometry={nodes.zewn_12.geometry}
        material={nodes.zewn_12.material}
        position={[2.514, 5.6, -12.994]}
      />
      <mesh
        geometry={nodes.zewn_9.geometry}
        material={nodes.zewn_9.material}
        position={[9.167, 3.636, -8.305]}
      />
      <mesh
        geometry={nodes.zewn_23.geometry}
        material={nodes.zewn_23.material}
        position={[9, 2.668, -8.707]}
      />
      <mesh
        geometry={nodes.zewn_8.geometry}
        material={nodes.zewn_8.material}
        position={[7.87, 3, 6.48]}
      />
      <mesh
        geometry={nodes.zewn_14.geometry}
        material={nodes.zewn_14.material}
        position={[-5.403, 2, -3.873]}
      />
      <mesh
        geometry={nodes.sufit001.geometry}
        material={nodes.sufit001.material}
        position={[1.037, 6.953, -0.41]}
        scale={0.005}
      />
      <mesh
        geometry={nodes.zewn_23001.geometry}
        material={nodes.zewn_23001.material}
        position={[9.049, -1.345, -8.707]}
      />
      <mesh
        geometry={nodes.zewn_23002.geometry}
        material={nodes.zewn_23002.material}
        position={[4.792, -1.309, 0.677]}
        rotation={[-Math.PI, 0, -Math.PI]}
      />
      <mesh
        geometry={nodes.zewn_23003.geometry}
        material={nodes.zewn_23003.material}
        position={[8.375, -1.345, 4.149]}
        rotation={[0, -0.108, 0]}
      />
      <mesh
        geometry={nodes.zewn_23004.geometry}
        material={nodes.zewn_23004.material}
        position={[1.155, -1.309, -14.193]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        geometry={nodes.zewn_23005.geometry}
        material={nodes.zewn_23005.material}
        position={[3.31, -1.341, -6.232]}
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        position={[6.32, -0.074, -2.395]}
        scale={[2.684, 2.323, 11.953]}
      />
    </group>
  );
}

useGLTF.preload("/gallery.glb");
